NodeArchive node_archive

string[] object_keys # for the same action nodes this should be all the same
string[] object_names # for the same action nodes this may be different based on the task

# defined enum class in data_type.hpp
int32 tree_phase

---
bool is_accepted
string message

string skill_parameters_json
