int32 ERROR=-1
int32 IDLE=0
int32 RESUME=1
int32 PAUSE=2
int32 SUCCESS=3
int32 FAILURE=4
int32 FINISH=5

string client_name "god"
int32 tree_phase 0
string reason "BB: You left the reason empty. Shame on you."
---
bool is_accepted