########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindPoco.cmake")
set(Poco_FOUND 1)
set(Poco_VERSION "1.11.0")

find_package_handle_standard_args(Poco REQUIRED_VARS
                                  Poco_VERSION VERSION_VAR Poco_VERSION)
mark_as_advanced(Poco_FOUND Poco_VERSION)

set(Poco_COMPONENTS Poco::DataMySQL Poco::DataPostgreSQL Poco::DataSQLite Poco::Encodings Poco::JWT Poco::MongoDB Poco::NetSSL Poco::Crypto Poco::Redis Poco::Net Poco::Zip Poco::Util Poco::JSON Poco::XML Poco::ActiveRecord Poco::Data Poco::Foundation)

if(Poco_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${Poco_FIND_COMPONENTS})
        list(FIND Poco_COMPONENTS "Poco::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'Poco'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'Poco'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(Poco_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_RES_DIRS )
set(Poco_DEFINITIONS "-DPOCO_STATIC=ON"
			"-DPOCO_UNBUNDLED")
set(Poco_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(Poco_COMPILE_DEFINITIONS "POCO_STATIC=ON"
			"POCO_UNBUNDLED")
set(Poco_COMPILE_OPTIONS_LIST "" "")
set(Poco_COMPILE_OPTIONS_C "")
set(Poco_COMPILE_OPTIONS_CXX "")
set(Poco_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(Poco_LIBRARIES "") # Will be filled later
set(Poco_LIBS "") # Same as Poco_LIBRARIES
set(Poco_SYSTEM_LIBS pthread dl rt)
set(Poco_FRAMEWORK_DIRS )
set(Poco_FRAMEWORKS )
set(Poco_FRAMEWORKS_FOUND "") # Will be filled later
set(Poco_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(Poco_FRAMEWORKS_FOUND "${Poco_FRAMEWORKS}" "${Poco_FRAMEWORK_DIRS}")

mark_as_advanced(Poco_INCLUDE_DIRS
                 Poco_INCLUDE_DIR
                 Poco_INCLUDES
                 Poco_DEFINITIONS
                 Poco_LINKER_FLAGS_LIST
                 Poco_COMPILE_DEFINITIONS
                 Poco_COMPILE_OPTIONS_LIST
                 Poco_LIBRARIES
                 Poco_LIBS
                 Poco_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to Poco_LIBS and Poco_LIBRARY_LIST
set(Poco_LIBRARY_LIST PocoDataMySQL PocoDataPostgreSQL PocoDataSQLite PocoEncodings PocoJWT PocoMongoDB PocoNetSSL PocoCrypto PocoRedis PocoNet PocoZip PocoUtil PocoJSON PocoXML PocoActiveRecord PocoData PocoFoundation)
set(Poco_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_Poco_DEPENDENCIES "${Poco_FRAMEWORKS_FOUND} ${Poco_SYSTEM_LIBS} MySQL::MySQL;PostgreSQL::PostgreSQL;SQLite::SQLite;OpenSSL::OpenSSL;EXPAT::EXPAT;PCRE::PCRE;ZLIB::ZLIB")

conan_package_library_targets("${Poco_LIBRARY_LIST}"  # libraries
                              "${Poco_LIB_DIRS}"      # package_libdir
                              "${_Poco_DEPENDENCIES}"  # deps
                              Poco_LIBRARIES            # out_libraries
                              Poco_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "Poco")                                      # package_name

set(Poco_LIBS ${Poco_LIBRARIES})

foreach(_FRAMEWORK ${Poco_FRAMEWORKS_FOUND})
    list(APPEND Poco_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND Poco_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${Poco_SYSTEM_LIBS})
    list(APPEND Poco_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND Poco_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(Poco_LIBRARIES_TARGETS "${Poco_LIBRARIES_TARGETS};MySQL::MySQL;PostgreSQL::PostgreSQL;SQLite::SQLite;OpenSSL::OpenSSL;EXPAT::EXPAT;PCRE::PCRE;ZLIB::ZLIB")
set(Poco_LIBRARIES "${Poco_LIBRARIES};MySQL::MySQL;PostgreSQL::PostgreSQL;SQLite::SQLite;OpenSSL::OpenSSL;EXPAT::EXPAT;PCRE::PCRE;ZLIB::ZLIB")

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})


########### COMPONENT Foundation VARIABLES #############################################

set(Poco_Foundation_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Foundation_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Foundation_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Foundation_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Foundation_RES_DIRS )
set(Poco_Foundation_DEFINITIONS "-DPOCO_STATIC=ON"
			"-DPOCO_UNBUNDLED")
set(Poco_Foundation_COMPILE_DEFINITIONS "POCO_STATIC=ON"
			"POCO_UNBUNDLED")
set(Poco_Foundation_COMPILE_OPTIONS_C "")
set(Poco_Foundation_COMPILE_OPTIONS_CXX "")
set(Poco_Foundation_LIBS PocoFoundation)
set(Poco_Foundation_SYSTEM_LIBS pthread dl rt)
set(Poco_Foundation_FRAMEWORK_DIRS )
set(Poco_Foundation_FRAMEWORKS )
set(Poco_Foundation_BUILD_MODULES_PATHS )
set(Poco_Foundation_DEPENDENCIES PCRE::PCRE ZLIB::ZLIB)
set(Poco_Foundation_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Data VARIABLES #############################################

set(Poco_Data_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Data_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Data_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Data_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Data_RES_DIRS )
set(Poco_Data_DEFINITIONS )
set(Poco_Data_COMPILE_DEFINITIONS )
set(Poco_Data_COMPILE_OPTIONS_C "")
set(Poco_Data_COMPILE_OPTIONS_CXX "")
set(Poco_Data_LIBS PocoData)
set(Poco_Data_SYSTEM_LIBS )
set(Poco_Data_FRAMEWORK_DIRS )
set(Poco_Data_FRAMEWORKS )
set(Poco_Data_BUILD_MODULES_PATHS )
set(Poco_Data_DEPENDENCIES Poco::Foundation)
set(Poco_Data_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT ActiveRecord VARIABLES #############################################

set(Poco_ActiveRecord_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_ActiveRecord_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_ActiveRecord_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_ActiveRecord_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_ActiveRecord_RES_DIRS )
set(Poco_ActiveRecord_DEFINITIONS )
set(Poco_ActiveRecord_COMPILE_DEFINITIONS )
set(Poco_ActiveRecord_COMPILE_OPTIONS_C "")
set(Poco_ActiveRecord_COMPILE_OPTIONS_CXX "")
set(Poco_ActiveRecord_LIBS PocoActiveRecord)
set(Poco_ActiveRecord_SYSTEM_LIBS )
set(Poco_ActiveRecord_FRAMEWORK_DIRS )
set(Poco_ActiveRecord_FRAMEWORKS )
set(Poco_ActiveRecord_BUILD_MODULES_PATHS )
set(Poco_ActiveRecord_DEPENDENCIES Poco::Foundation Poco::Data)
set(Poco_ActiveRecord_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT XML VARIABLES #############################################

set(Poco_XML_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_XML_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_XML_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_XML_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_XML_RES_DIRS )
set(Poco_XML_DEFINITIONS )
set(Poco_XML_COMPILE_DEFINITIONS )
set(Poco_XML_COMPILE_OPTIONS_C "")
set(Poco_XML_COMPILE_OPTIONS_CXX "")
set(Poco_XML_LIBS PocoXML)
set(Poco_XML_SYSTEM_LIBS )
set(Poco_XML_FRAMEWORK_DIRS )
set(Poco_XML_FRAMEWORKS )
set(Poco_XML_BUILD_MODULES_PATHS )
set(Poco_XML_DEPENDENCIES Poco::Foundation EXPAT::EXPAT)
set(Poco_XML_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT JSON VARIABLES #############################################

set(Poco_JSON_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_JSON_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_JSON_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_JSON_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_JSON_RES_DIRS )
set(Poco_JSON_DEFINITIONS )
set(Poco_JSON_COMPILE_DEFINITIONS )
set(Poco_JSON_COMPILE_OPTIONS_C "")
set(Poco_JSON_COMPILE_OPTIONS_CXX "")
set(Poco_JSON_LIBS PocoJSON)
set(Poco_JSON_SYSTEM_LIBS )
set(Poco_JSON_FRAMEWORK_DIRS )
set(Poco_JSON_FRAMEWORKS )
set(Poco_JSON_BUILD_MODULES_PATHS )
set(Poco_JSON_DEPENDENCIES Poco::Foundation)
set(Poco_JSON_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Util VARIABLES #############################################

set(Poco_Util_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Util_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Util_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Util_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Util_RES_DIRS )
set(Poco_Util_DEFINITIONS )
set(Poco_Util_COMPILE_DEFINITIONS )
set(Poco_Util_COMPILE_OPTIONS_C "")
set(Poco_Util_COMPILE_OPTIONS_CXX "")
set(Poco_Util_LIBS PocoUtil)
set(Poco_Util_SYSTEM_LIBS )
set(Poco_Util_FRAMEWORK_DIRS )
set(Poco_Util_FRAMEWORKS )
set(Poco_Util_BUILD_MODULES_PATHS )
set(Poco_Util_DEPENDENCIES Poco::Foundation Poco::XML Poco::JSON)
set(Poco_Util_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Zip VARIABLES #############################################

set(Poco_Zip_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Zip_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Zip_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Zip_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Zip_RES_DIRS )
set(Poco_Zip_DEFINITIONS )
set(Poco_Zip_COMPILE_DEFINITIONS )
set(Poco_Zip_COMPILE_OPTIONS_C "")
set(Poco_Zip_COMPILE_OPTIONS_CXX "")
set(Poco_Zip_LIBS PocoZip)
set(Poco_Zip_SYSTEM_LIBS )
set(Poco_Zip_FRAMEWORK_DIRS )
set(Poco_Zip_FRAMEWORKS )
set(Poco_Zip_BUILD_MODULES_PATHS )
set(Poco_Zip_DEPENDENCIES Poco::Util Poco::XML)
set(Poco_Zip_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Net VARIABLES #############################################

set(Poco_Net_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Net_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Net_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Net_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Net_RES_DIRS )
set(Poco_Net_DEFINITIONS )
set(Poco_Net_COMPILE_DEFINITIONS )
set(Poco_Net_COMPILE_OPTIONS_C "")
set(Poco_Net_COMPILE_OPTIONS_CXX "")
set(Poco_Net_LIBS PocoNet)
set(Poco_Net_SYSTEM_LIBS )
set(Poco_Net_FRAMEWORK_DIRS )
set(Poco_Net_FRAMEWORKS )
set(Poco_Net_BUILD_MODULES_PATHS )
set(Poco_Net_DEPENDENCIES Poco::Foundation)
set(Poco_Net_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Redis VARIABLES #############################################

set(Poco_Redis_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Redis_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Redis_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Redis_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Redis_RES_DIRS )
set(Poco_Redis_DEFINITIONS )
set(Poco_Redis_COMPILE_DEFINITIONS )
set(Poco_Redis_COMPILE_OPTIONS_C "")
set(Poco_Redis_COMPILE_OPTIONS_CXX "")
set(Poco_Redis_LIBS PocoRedis)
set(Poco_Redis_SYSTEM_LIBS )
set(Poco_Redis_FRAMEWORK_DIRS )
set(Poco_Redis_FRAMEWORKS )
set(Poco_Redis_BUILD_MODULES_PATHS )
set(Poco_Redis_DEPENDENCIES Poco::Net)
set(Poco_Redis_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Crypto VARIABLES #############################################

set(Poco_Crypto_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Crypto_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Crypto_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Crypto_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Crypto_RES_DIRS )
set(Poco_Crypto_DEFINITIONS )
set(Poco_Crypto_COMPILE_DEFINITIONS )
set(Poco_Crypto_COMPILE_OPTIONS_C "")
set(Poco_Crypto_COMPILE_OPTIONS_CXX "")
set(Poco_Crypto_LIBS PocoCrypto)
set(Poco_Crypto_SYSTEM_LIBS )
set(Poco_Crypto_FRAMEWORK_DIRS )
set(Poco_Crypto_FRAMEWORKS )
set(Poco_Crypto_BUILD_MODULES_PATHS )
set(Poco_Crypto_DEPENDENCIES Poco::Foundation OpenSSL::OpenSSL)
set(Poco_Crypto_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT NetSSL VARIABLES #############################################

set(Poco_NetSSL_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_NetSSL_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_NetSSL_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_NetSSL_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_NetSSL_RES_DIRS )
set(Poco_NetSSL_DEFINITIONS )
set(Poco_NetSSL_COMPILE_DEFINITIONS )
set(Poco_NetSSL_COMPILE_OPTIONS_C "")
set(Poco_NetSSL_COMPILE_OPTIONS_CXX "")
set(Poco_NetSSL_LIBS PocoNetSSL)
set(Poco_NetSSL_SYSTEM_LIBS )
set(Poco_NetSSL_FRAMEWORK_DIRS )
set(Poco_NetSSL_FRAMEWORKS )
set(Poco_NetSSL_BUILD_MODULES_PATHS )
set(Poco_NetSSL_DEPENDENCIES Poco::Crypto Poco::Util Poco::Net)
set(Poco_NetSSL_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT MongoDB VARIABLES #############################################

set(Poco_MongoDB_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_MongoDB_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_MongoDB_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_MongoDB_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_MongoDB_RES_DIRS )
set(Poco_MongoDB_DEFINITIONS )
set(Poco_MongoDB_COMPILE_DEFINITIONS )
set(Poco_MongoDB_COMPILE_OPTIONS_C "")
set(Poco_MongoDB_COMPILE_OPTIONS_CXX "")
set(Poco_MongoDB_LIBS PocoMongoDB)
set(Poco_MongoDB_SYSTEM_LIBS )
set(Poco_MongoDB_FRAMEWORK_DIRS )
set(Poco_MongoDB_FRAMEWORKS )
set(Poco_MongoDB_BUILD_MODULES_PATHS )
set(Poco_MongoDB_DEPENDENCIES Poco::Net)
set(Poco_MongoDB_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT JWT VARIABLES #############################################

set(Poco_JWT_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_JWT_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_JWT_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_JWT_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_JWT_RES_DIRS )
set(Poco_JWT_DEFINITIONS )
set(Poco_JWT_COMPILE_DEFINITIONS )
set(Poco_JWT_COMPILE_OPTIONS_C "")
set(Poco_JWT_COMPILE_OPTIONS_CXX "")
set(Poco_JWT_LIBS PocoJWT)
set(Poco_JWT_SYSTEM_LIBS )
set(Poco_JWT_FRAMEWORK_DIRS )
set(Poco_JWT_FRAMEWORKS )
set(Poco_JWT_BUILD_MODULES_PATHS )
set(Poco_JWT_DEPENDENCIES Poco::JSON Poco::Crypto)
set(Poco_JWT_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Encodings VARIABLES #############################################

set(Poco_Encodings_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Encodings_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Encodings_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_Encodings_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_Encodings_RES_DIRS )
set(Poco_Encodings_DEFINITIONS )
set(Poco_Encodings_COMPILE_DEFINITIONS )
set(Poco_Encodings_COMPILE_OPTIONS_C "")
set(Poco_Encodings_COMPILE_OPTIONS_CXX "")
set(Poco_Encodings_LIBS PocoEncodings)
set(Poco_Encodings_SYSTEM_LIBS )
set(Poco_Encodings_FRAMEWORK_DIRS )
set(Poco_Encodings_FRAMEWORKS )
set(Poco_Encodings_BUILD_MODULES_PATHS )
set(Poco_Encodings_DEPENDENCIES Poco::Foundation)
set(Poco_Encodings_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT DataSQLite VARIABLES #############################################

set(Poco_DataSQLite_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataSQLite_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataSQLite_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataSQLite_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_DataSQLite_RES_DIRS )
set(Poco_DataSQLite_DEFINITIONS )
set(Poco_DataSQLite_COMPILE_DEFINITIONS )
set(Poco_DataSQLite_COMPILE_OPTIONS_C "")
set(Poco_DataSQLite_COMPILE_OPTIONS_CXX "")
set(Poco_DataSQLite_LIBS PocoDataSQLite)
set(Poco_DataSQLite_SYSTEM_LIBS )
set(Poco_DataSQLite_FRAMEWORK_DIRS )
set(Poco_DataSQLite_FRAMEWORKS )
set(Poco_DataSQLite_BUILD_MODULES_PATHS )
set(Poco_DataSQLite_DEPENDENCIES Poco::Data SQLite::SQLite)
set(Poco_DataSQLite_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT DataPostgreSQL VARIABLES #############################################

set(Poco_DataPostgreSQL_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataPostgreSQL_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataPostgreSQL_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataPostgreSQL_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_DataPostgreSQL_RES_DIRS )
set(Poco_DataPostgreSQL_DEFINITIONS )
set(Poco_DataPostgreSQL_COMPILE_DEFINITIONS )
set(Poco_DataPostgreSQL_COMPILE_OPTIONS_C "")
set(Poco_DataPostgreSQL_COMPILE_OPTIONS_CXX "")
set(Poco_DataPostgreSQL_LIBS PocoDataPostgreSQL)
set(Poco_DataPostgreSQL_SYSTEM_LIBS )
set(Poco_DataPostgreSQL_FRAMEWORK_DIRS )
set(Poco_DataPostgreSQL_FRAMEWORKS )
set(Poco_DataPostgreSQL_BUILD_MODULES_PATHS )
set(Poco_DataPostgreSQL_DEPENDENCIES Poco::Data PostgreSQL::PostgreSQL)
set(Poco_DataPostgreSQL_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT DataMySQL VARIABLES #############################################

set(Poco_DataMySQL_INCLUDE_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataMySQL_INCLUDE_DIR "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataMySQL_INCLUDES "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/include")
set(Poco_DataMySQL_LIB_DIRS "/home/blackbird/.conan/data/poco/1.11.0/_/_/package/68684f3caf2a75d1ab629579551ce1eeeddefe1b/lib")
set(Poco_DataMySQL_RES_DIRS )
set(Poco_DataMySQL_DEFINITIONS )
set(Poco_DataMySQL_COMPILE_DEFINITIONS )
set(Poco_DataMySQL_COMPILE_OPTIONS_C "")
set(Poco_DataMySQL_COMPILE_OPTIONS_CXX "")
set(Poco_DataMySQL_LIBS PocoDataMySQL)
set(Poco_DataMySQL_SYSTEM_LIBS )
set(Poco_DataMySQL_FRAMEWORK_DIRS )
set(Poco_DataMySQL_FRAMEWORKS )
set(Poco_DataMySQL_BUILD_MODULES_PATHS )
set(Poco_DataMySQL_DEPENDENCIES Poco::Data MySQL::MySQL)
set(Poco_DataMySQL_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)

if(NOT MySQL_FOUND)
    find_dependency(MySQL REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency MySQL already found")
endif()

if(NOT PostgreSQL_FOUND)
    find_dependency(PostgreSQL REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency PostgreSQL already found")
endif()

if(NOT SQLite3_FOUND)
    find_dependency(SQLite3 REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency SQLite3 already found")
endif()

if(NOT OpenSSL_FOUND)
    find_dependency(OpenSSL REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency OpenSSL already found")
endif()

if(NOT EXPAT_FOUND)
    find_dependency(EXPAT REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency EXPAT already found")
endif()

if(NOT PCRE_FOUND)
    find_dependency(PCRE REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency PCRE already found")
endif()

if(NOT ZLIB_FOUND)
    find_dependency(ZLIB REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency ZLIB already found")
endif()


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT Foundation FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Foundation_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Foundation_FRAMEWORKS_FOUND "${Poco_Foundation_FRAMEWORKS}" "${Poco_Foundation_FRAMEWORK_DIRS}")

set(Poco_Foundation_LIB_TARGETS "")
set(Poco_Foundation_NOT_USED "")
set(Poco_Foundation_LIBS_FRAMEWORKS_DEPS ${Poco_Foundation_FRAMEWORKS_FOUND} ${Poco_Foundation_SYSTEM_LIBS} ${Poco_Foundation_DEPENDENCIES})
conan_package_library_targets("${Poco_Foundation_LIBS}"
                              "${Poco_Foundation_LIB_DIRS}"
                              "${Poco_Foundation_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Foundation_NOT_USED
                              Poco_Foundation_LIB_TARGETS
                              ""
                              "Poco_Foundation")

set(Poco_Foundation_LINK_LIBS ${Poco_Foundation_LIB_TARGETS} ${Poco_Foundation_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Data FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Data_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Data_FRAMEWORKS_FOUND "${Poco_Data_FRAMEWORKS}" "${Poco_Data_FRAMEWORK_DIRS}")

set(Poco_Data_LIB_TARGETS "")
set(Poco_Data_NOT_USED "")
set(Poco_Data_LIBS_FRAMEWORKS_DEPS ${Poco_Data_FRAMEWORKS_FOUND} ${Poco_Data_SYSTEM_LIBS} ${Poco_Data_DEPENDENCIES})
conan_package_library_targets("${Poco_Data_LIBS}"
                              "${Poco_Data_LIB_DIRS}"
                              "${Poco_Data_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Data_NOT_USED
                              Poco_Data_LIB_TARGETS
                              ""
                              "Poco_Data")

set(Poco_Data_LINK_LIBS ${Poco_Data_LIB_TARGETS} ${Poco_Data_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT ActiveRecord FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_ActiveRecord_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_ActiveRecord_FRAMEWORKS_FOUND "${Poco_ActiveRecord_FRAMEWORKS}" "${Poco_ActiveRecord_FRAMEWORK_DIRS}")

set(Poco_ActiveRecord_LIB_TARGETS "")
set(Poco_ActiveRecord_NOT_USED "")
set(Poco_ActiveRecord_LIBS_FRAMEWORKS_DEPS ${Poco_ActiveRecord_FRAMEWORKS_FOUND} ${Poco_ActiveRecord_SYSTEM_LIBS} ${Poco_ActiveRecord_DEPENDENCIES})
conan_package_library_targets("${Poco_ActiveRecord_LIBS}"
                              "${Poco_ActiveRecord_LIB_DIRS}"
                              "${Poco_ActiveRecord_LIBS_FRAMEWORKS_DEPS}"
                              Poco_ActiveRecord_NOT_USED
                              Poco_ActiveRecord_LIB_TARGETS
                              ""
                              "Poco_ActiveRecord")

set(Poco_ActiveRecord_LINK_LIBS ${Poco_ActiveRecord_LIB_TARGETS} ${Poco_ActiveRecord_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT XML FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_XML_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_XML_FRAMEWORKS_FOUND "${Poco_XML_FRAMEWORKS}" "${Poco_XML_FRAMEWORK_DIRS}")

set(Poco_XML_LIB_TARGETS "")
set(Poco_XML_NOT_USED "")
set(Poco_XML_LIBS_FRAMEWORKS_DEPS ${Poco_XML_FRAMEWORKS_FOUND} ${Poco_XML_SYSTEM_LIBS} ${Poco_XML_DEPENDENCIES})
conan_package_library_targets("${Poco_XML_LIBS}"
                              "${Poco_XML_LIB_DIRS}"
                              "${Poco_XML_LIBS_FRAMEWORKS_DEPS}"
                              Poco_XML_NOT_USED
                              Poco_XML_LIB_TARGETS
                              ""
                              "Poco_XML")

set(Poco_XML_LINK_LIBS ${Poco_XML_LIB_TARGETS} ${Poco_XML_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT JSON FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_JSON_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_JSON_FRAMEWORKS_FOUND "${Poco_JSON_FRAMEWORKS}" "${Poco_JSON_FRAMEWORK_DIRS}")

set(Poco_JSON_LIB_TARGETS "")
set(Poco_JSON_NOT_USED "")
set(Poco_JSON_LIBS_FRAMEWORKS_DEPS ${Poco_JSON_FRAMEWORKS_FOUND} ${Poco_JSON_SYSTEM_LIBS} ${Poco_JSON_DEPENDENCIES})
conan_package_library_targets("${Poco_JSON_LIBS}"
                              "${Poco_JSON_LIB_DIRS}"
                              "${Poco_JSON_LIBS_FRAMEWORKS_DEPS}"
                              Poco_JSON_NOT_USED
                              Poco_JSON_LIB_TARGETS
                              ""
                              "Poco_JSON")

set(Poco_JSON_LINK_LIBS ${Poco_JSON_LIB_TARGETS} ${Poco_JSON_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Util FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Util_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Util_FRAMEWORKS_FOUND "${Poco_Util_FRAMEWORKS}" "${Poco_Util_FRAMEWORK_DIRS}")

set(Poco_Util_LIB_TARGETS "")
set(Poco_Util_NOT_USED "")
set(Poco_Util_LIBS_FRAMEWORKS_DEPS ${Poco_Util_FRAMEWORKS_FOUND} ${Poco_Util_SYSTEM_LIBS} ${Poco_Util_DEPENDENCIES})
conan_package_library_targets("${Poco_Util_LIBS}"
                              "${Poco_Util_LIB_DIRS}"
                              "${Poco_Util_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Util_NOT_USED
                              Poco_Util_LIB_TARGETS
                              ""
                              "Poco_Util")

set(Poco_Util_LINK_LIBS ${Poco_Util_LIB_TARGETS} ${Poco_Util_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Zip FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Zip_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Zip_FRAMEWORKS_FOUND "${Poco_Zip_FRAMEWORKS}" "${Poco_Zip_FRAMEWORK_DIRS}")

set(Poco_Zip_LIB_TARGETS "")
set(Poco_Zip_NOT_USED "")
set(Poco_Zip_LIBS_FRAMEWORKS_DEPS ${Poco_Zip_FRAMEWORKS_FOUND} ${Poco_Zip_SYSTEM_LIBS} ${Poco_Zip_DEPENDENCIES})
conan_package_library_targets("${Poco_Zip_LIBS}"
                              "${Poco_Zip_LIB_DIRS}"
                              "${Poco_Zip_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Zip_NOT_USED
                              Poco_Zip_LIB_TARGETS
                              ""
                              "Poco_Zip")

set(Poco_Zip_LINK_LIBS ${Poco_Zip_LIB_TARGETS} ${Poco_Zip_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Net FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Net_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Net_FRAMEWORKS_FOUND "${Poco_Net_FRAMEWORKS}" "${Poco_Net_FRAMEWORK_DIRS}")

set(Poco_Net_LIB_TARGETS "")
set(Poco_Net_NOT_USED "")
set(Poco_Net_LIBS_FRAMEWORKS_DEPS ${Poco_Net_FRAMEWORKS_FOUND} ${Poco_Net_SYSTEM_LIBS} ${Poco_Net_DEPENDENCIES})
conan_package_library_targets("${Poco_Net_LIBS}"
                              "${Poco_Net_LIB_DIRS}"
                              "${Poco_Net_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Net_NOT_USED
                              Poco_Net_LIB_TARGETS
                              ""
                              "Poco_Net")

set(Poco_Net_LINK_LIBS ${Poco_Net_LIB_TARGETS} ${Poco_Net_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Redis FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Redis_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Redis_FRAMEWORKS_FOUND "${Poco_Redis_FRAMEWORKS}" "${Poco_Redis_FRAMEWORK_DIRS}")

set(Poco_Redis_LIB_TARGETS "")
set(Poco_Redis_NOT_USED "")
set(Poco_Redis_LIBS_FRAMEWORKS_DEPS ${Poco_Redis_FRAMEWORKS_FOUND} ${Poco_Redis_SYSTEM_LIBS} ${Poco_Redis_DEPENDENCIES})
conan_package_library_targets("${Poco_Redis_LIBS}"
                              "${Poco_Redis_LIB_DIRS}"
                              "${Poco_Redis_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Redis_NOT_USED
                              Poco_Redis_LIB_TARGETS
                              ""
                              "Poco_Redis")

set(Poco_Redis_LINK_LIBS ${Poco_Redis_LIB_TARGETS} ${Poco_Redis_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Crypto FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Crypto_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Crypto_FRAMEWORKS_FOUND "${Poco_Crypto_FRAMEWORKS}" "${Poco_Crypto_FRAMEWORK_DIRS}")

set(Poco_Crypto_LIB_TARGETS "")
set(Poco_Crypto_NOT_USED "")
set(Poco_Crypto_LIBS_FRAMEWORKS_DEPS ${Poco_Crypto_FRAMEWORKS_FOUND} ${Poco_Crypto_SYSTEM_LIBS} ${Poco_Crypto_DEPENDENCIES})
conan_package_library_targets("${Poco_Crypto_LIBS}"
                              "${Poco_Crypto_LIB_DIRS}"
                              "${Poco_Crypto_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Crypto_NOT_USED
                              Poco_Crypto_LIB_TARGETS
                              ""
                              "Poco_Crypto")

set(Poco_Crypto_LINK_LIBS ${Poco_Crypto_LIB_TARGETS} ${Poco_Crypto_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT NetSSL FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_NetSSL_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_NetSSL_FRAMEWORKS_FOUND "${Poco_NetSSL_FRAMEWORKS}" "${Poco_NetSSL_FRAMEWORK_DIRS}")

set(Poco_NetSSL_LIB_TARGETS "")
set(Poco_NetSSL_NOT_USED "")
set(Poco_NetSSL_LIBS_FRAMEWORKS_DEPS ${Poco_NetSSL_FRAMEWORKS_FOUND} ${Poco_NetSSL_SYSTEM_LIBS} ${Poco_NetSSL_DEPENDENCIES})
conan_package_library_targets("${Poco_NetSSL_LIBS}"
                              "${Poco_NetSSL_LIB_DIRS}"
                              "${Poco_NetSSL_LIBS_FRAMEWORKS_DEPS}"
                              Poco_NetSSL_NOT_USED
                              Poco_NetSSL_LIB_TARGETS
                              ""
                              "Poco_NetSSL")

set(Poco_NetSSL_LINK_LIBS ${Poco_NetSSL_LIB_TARGETS} ${Poco_NetSSL_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT MongoDB FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_MongoDB_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_MongoDB_FRAMEWORKS_FOUND "${Poco_MongoDB_FRAMEWORKS}" "${Poco_MongoDB_FRAMEWORK_DIRS}")

set(Poco_MongoDB_LIB_TARGETS "")
set(Poco_MongoDB_NOT_USED "")
set(Poco_MongoDB_LIBS_FRAMEWORKS_DEPS ${Poco_MongoDB_FRAMEWORKS_FOUND} ${Poco_MongoDB_SYSTEM_LIBS} ${Poco_MongoDB_DEPENDENCIES})
conan_package_library_targets("${Poco_MongoDB_LIBS}"
                              "${Poco_MongoDB_LIB_DIRS}"
                              "${Poco_MongoDB_LIBS_FRAMEWORKS_DEPS}"
                              Poco_MongoDB_NOT_USED
                              Poco_MongoDB_LIB_TARGETS
                              ""
                              "Poco_MongoDB")

set(Poco_MongoDB_LINK_LIBS ${Poco_MongoDB_LIB_TARGETS} ${Poco_MongoDB_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT JWT FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_JWT_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_JWT_FRAMEWORKS_FOUND "${Poco_JWT_FRAMEWORKS}" "${Poco_JWT_FRAMEWORK_DIRS}")

set(Poco_JWT_LIB_TARGETS "")
set(Poco_JWT_NOT_USED "")
set(Poco_JWT_LIBS_FRAMEWORKS_DEPS ${Poco_JWT_FRAMEWORKS_FOUND} ${Poco_JWT_SYSTEM_LIBS} ${Poco_JWT_DEPENDENCIES})
conan_package_library_targets("${Poco_JWT_LIBS}"
                              "${Poco_JWT_LIB_DIRS}"
                              "${Poco_JWT_LIBS_FRAMEWORKS_DEPS}"
                              Poco_JWT_NOT_USED
                              Poco_JWT_LIB_TARGETS
                              ""
                              "Poco_JWT")

set(Poco_JWT_LINK_LIBS ${Poco_JWT_LIB_TARGETS} ${Poco_JWT_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT Encodings FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_Encodings_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_Encodings_FRAMEWORKS_FOUND "${Poco_Encodings_FRAMEWORKS}" "${Poco_Encodings_FRAMEWORK_DIRS}")

set(Poco_Encodings_LIB_TARGETS "")
set(Poco_Encodings_NOT_USED "")
set(Poco_Encodings_LIBS_FRAMEWORKS_DEPS ${Poco_Encodings_FRAMEWORKS_FOUND} ${Poco_Encodings_SYSTEM_LIBS} ${Poco_Encodings_DEPENDENCIES})
conan_package_library_targets("${Poco_Encodings_LIBS}"
                              "${Poco_Encodings_LIB_DIRS}"
                              "${Poco_Encodings_LIBS_FRAMEWORKS_DEPS}"
                              Poco_Encodings_NOT_USED
                              Poco_Encodings_LIB_TARGETS
                              ""
                              "Poco_Encodings")

set(Poco_Encodings_LINK_LIBS ${Poco_Encodings_LIB_TARGETS} ${Poco_Encodings_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT DataSQLite FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_DataSQLite_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_DataSQLite_FRAMEWORKS_FOUND "${Poco_DataSQLite_FRAMEWORKS}" "${Poco_DataSQLite_FRAMEWORK_DIRS}")

set(Poco_DataSQLite_LIB_TARGETS "")
set(Poco_DataSQLite_NOT_USED "")
set(Poco_DataSQLite_LIBS_FRAMEWORKS_DEPS ${Poco_DataSQLite_FRAMEWORKS_FOUND} ${Poco_DataSQLite_SYSTEM_LIBS} ${Poco_DataSQLite_DEPENDENCIES})
conan_package_library_targets("${Poco_DataSQLite_LIBS}"
                              "${Poco_DataSQLite_LIB_DIRS}"
                              "${Poco_DataSQLite_LIBS_FRAMEWORKS_DEPS}"
                              Poco_DataSQLite_NOT_USED
                              Poco_DataSQLite_LIB_TARGETS
                              ""
                              "Poco_DataSQLite")

set(Poco_DataSQLite_LINK_LIBS ${Poco_DataSQLite_LIB_TARGETS} ${Poco_DataSQLite_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT DataPostgreSQL FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_DataPostgreSQL_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_DataPostgreSQL_FRAMEWORKS_FOUND "${Poco_DataPostgreSQL_FRAMEWORKS}" "${Poco_DataPostgreSQL_FRAMEWORK_DIRS}")

set(Poco_DataPostgreSQL_LIB_TARGETS "")
set(Poco_DataPostgreSQL_NOT_USED "")
set(Poco_DataPostgreSQL_LIBS_FRAMEWORKS_DEPS ${Poco_DataPostgreSQL_FRAMEWORKS_FOUND} ${Poco_DataPostgreSQL_SYSTEM_LIBS} ${Poco_DataPostgreSQL_DEPENDENCIES})
conan_package_library_targets("${Poco_DataPostgreSQL_LIBS}"
                              "${Poco_DataPostgreSQL_LIB_DIRS}"
                              "${Poco_DataPostgreSQL_LIBS_FRAMEWORKS_DEPS}"
                              Poco_DataPostgreSQL_NOT_USED
                              Poco_DataPostgreSQL_LIB_TARGETS
                              ""
                              "Poco_DataPostgreSQL")

set(Poco_DataPostgreSQL_LINK_LIBS ${Poco_DataPostgreSQL_LIB_TARGETS} ${Poco_DataPostgreSQL_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})

########## COMPONENT DataMySQL FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Poco_DataMySQL_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Poco_DataMySQL_FRAMEWORKS_FOUND "${Poco_DataMySQL_FRAMEWORKS}" "${Poco_DataMySQL_FRAMEWORK_DIRS}")

set(Poco_DataMySQL_LIB_TARGETS "")
set(Poco_DataMySQL_NOT_USED "")
set(Poco_DataMySQL_LIBS_FRAMEWORKS_DEPS ${Poco_DataMySQL_FRAMEWORKS_FOUND} ${Poco_DataMySQL_SYSTEM_LIBS} ${Poco_DataMySQL_DEPENDENCIES})
conan_package_library_targets("${Poco_DataMySQL_LIBS}"
                              "${Poco_DataMySQL_LIB_DIRS}"
                              "${Poco_DataMySQL_LIBS_FRAMEWORKS_DEPS}"
                              Poco_DataMySQL_NOT_USED
                              Poco_DataMySQL_LIB_TARGETS
                              ""
                              "Poco_DataMySQL")

set(Poco_DataMySQL_LINK_LIBS ${Poco_DataMySQL_LIB_TARGETS} ${Poco_DataMySQL_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT Foundation TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Foundation)
        add_library(Poco::Foundation INTERFACE IMPORTED)
        set_target_properties(Poco::Foundation PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Foundation_INCLUDE_DIRS}")
        set_target_properties(Poco::Foundation PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Foundation_LIB_DIRS}")
        set_target_properties(Poco::Foundation PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Foundation_LINK_LIBS};${Poco_Foundation_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Foundation PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Foundation_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Foundation PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Foundation_COMPILE_OPTIONS_C};${Poco_Foundation_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Data TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Data)
        add_library(Poco::Data INTERFACE IMPORTED)
        set_target_properties(Poco::Data PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Data_INCLUDE_DIRS}")
        set_target_properties(Poco::Data PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Data_LIB_DIRS}")
        set_target_properties(Poco::Data PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Data_LINK_LIBS};${Poco_Data_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Data PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Data_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Data PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Data_COMPILE_OPTIONS_C};${Poco_Data_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT ActiveRecord TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::ActiveRecord)
        add_library(Poco::ActiveRecord INTERFACE IMPORTED)
        set_target_properties(Poco::ActiveRecord PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_ActiveRecord_INCLUDE_DIRS}")
        set_target_properties(Poco::ActiveRecord PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_ActiveRecord_LIB_DIRS}")
        set_target_properties(Poco::ActiveRecord PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_ActiveRecord_LINK_LIBS};${Poco_ActiveRecord_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::ActiveRecord PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_ActiveRecord_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::ActiveRecord PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_ActiveRecord_COMPILE_OPTIONS_C};${Poco_ActiveRecord_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT XML TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::XML)
        add_library(Poco::XML INTERFACE IMPORTED)
        set_target_properties(Poco::XML PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_XML_INCLUDE_DIRS}")
        set_target_properties(Poco::XML PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_XML_LIB_DIRS}")
        set_target_properties(Poco::XML PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_XML_LINK_LIBS};${Poco_XML_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::XML PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_XML_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::XML PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_XML_COMPILE_OPTIONS_C};${Poco_XML_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT JSON TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::JSON)
        add_library(Poco::JSON INTERFACE IMPORTED)
        set_target_properties(Poco::JSON PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_JSON_INCLUDE_DIRS}")
        set_target_properties(Poco::JSON PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_JSON_LIB_DIRS}")
        set_target_properties(Poco::JSON PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_JSON_LINK_LIBS};${Poco_JSON_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::JSON PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_JSON_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::JSON PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_JSON_COMPILE_OPTIONS_C};${Poco_JSON_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Util TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Util)
        add_library(Poco::Util INTERFACE IMPORTED)
        set_target_properties(Poco::Util PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Util_INCLUDE_DIRS}")
        set_target_properties(Poco::Util PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Util_LIB_DIRS}")
        set_target_properties(Poco::Util PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Util_LINK_LIBS};${Poco_Util_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Util PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Util_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Util PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Util_COMPILE_OPTIONS_C};${Poco_Util_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Zip TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Zip)
        add_library(Poco::Zip INTERFACE IMPORTED)
        set_target_properties(Poco::Zip PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Zip_INCLUDE_DIRS}")
        set_target_properties(Poco::Zip PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Zip_LIB_DIRS}")
        set_target_properties(Poco::Zip PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Zip_LINK_LIBS};${Poco_Zip_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Zip PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Zip_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Zip PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Zip_COMPILE_OPTIONS_C};${Poco_Zip_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Net TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Net)
        add_library(Poco::Net INTERFACE IMPORTED)
        set_target_properties(Poco::Net PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Net_INCLUDE_DIRS}")
        set_target_properties(Poco::Net PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Net_LIB_DIRS}")
        set_target_properties(Poco::Net PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Net_LINK_LIBS};${Poco_Net_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Net PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Net_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Net PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Net_COMPILE_OPTIONS_C};${Poco_Net_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Redis TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Redis)
        add_library(Poco::Redis INTERFACE IMPORTED)
        set_target_properties(Poco::Redis PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Redis_INCLUDE_DIRS}")
        set_target_properties(Poco::Redis PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Redis_LIB_DIRS}")
        set_target_properties(Poco::Redis PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Redis_LINK_LIBS};${Poco_Redis_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Redis PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Redis_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Redis PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Redis_COMPILE_OPTIONS_C};${Poco_Redis_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Crypto TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Crypto)
        add_library(Poco::Crypto INTERFACE IMPORTED)
        set_target_properties(Poco::Crypto PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Crypto_INCLUDE_DIRS}")
        set_target_properties(Poco::Crypto PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Crypto_LIB_DIRS}")
        set_target_properties(Poco::Crypto PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Crypto_LINK_LIBS};${Poco_Crypto_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Crypto PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Crypto_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Crypto PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Crypto_COMPILE_OPTIONS_C};${Poco_Crypto_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT NetSSL TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::NetSSL)
        add_library(Poco::NetSSL INTERFACE IMPORTED)
        set_target_properties(Poco::NetSSL PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_NetSSL_INCLUDE_DIRS}")
        set_target_properties(Poco::NetSSL PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_NetSSL_LIB_DIRS}")
        set_target_properties(Poco::NetSSL PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_NetSSL_LINK_LIBS};${Poco_NetSSL_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::NetSSL PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_NetSSL_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::NetSSL PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_NetSSL_COMPILE_OPTIONS_C};${Poco_NetSSL_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT MongoDB TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::MongoDB)
        add_library(Poco::MongoDB INTERFACE IMPORTED)
        set_target_properties(Poco::MongoDB PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_MongoDB_INCLUDE_DIRS}")
        set_target_properties(Poco::MongoDB PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_MongoDB_LIB_DIRS}")
        set_target_properties(Poco::MongoDB PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_MongoDB_LINK_LIBS};${Poco_MongoDB_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::MongoDB PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_MongoDB_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::MongoDB PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_MongoDB_COMPILE_OPTIONS_C};${Poco_MongoDB_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT JWT TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::JWT)
        add_library(Poco::JWT INTERFACE IMPORTED)
        set_target_properties(Poco::JWT PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_JWT_INCLUDE_DIRS}")
        set_target_properties(Poco::JWT PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_JWT_LIB_DIRS}")
        set_target_properties(Poco::JWT PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_JWT_LINK_LIBS};${Poco_JWT_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::JWT PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_JWT_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::JWT PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_JWT_COMPILE_OPTIONS_C};${Poco_JWT_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Encodings TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::Encodings)
        add_library(Poco::Encodings INTERFACE IMPORTED)
        set_target_properties(Poco::Encodings PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_Encodings_INCLUDE_DIRS}")
        set_target_properties(Poco::Encodings PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_Encodings_LIB_DIRS}")
        set_target_properties(Poco::Encodings PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_Encodings_LINK_LIBS};${Poco_Encodings_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::Encodings PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_Encodings_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::Encodings PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_Encodings_COMPILE_OPTIONS_C};${Poco_Encodings_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT DataSQLite TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::DataSQLite)
        add_library(Poco::DataSQLite INTERFACE IMPORTED)
        set_target_properties(Poco::DataSQLite PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_DataSQLite_INCLUDE_DIRS}")
        set_target_properties(Poco::DataSQLite PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_DataSQLite_LIB_DIRS}")
        set_target_properties(Poco::DataSQLite PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_DataSQLite_LINK_LIBS};${Poco_DataSQLite_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::DataSQLite PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_DataSQLite_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::DataSQLite PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_DataSQLite_COMPILE_OPTIONS_C};${Poco_DataSQLite_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT DataPostgreSQL TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::DataPostgreSQL)
        add_library(Poco::DataPostgreSQL INTERFACE IMPORTED)
        set_target_properties(Poco::DataPostgreSQL PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_DataPostgreSQL_INCLUDE_DIRS}")
        set_target_properties(Poco::DataPostgreSQL PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_DataPostgreSQL_LIB_DIRS}")
        set_target_properties(Poco::DataPostgreSQL PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_DataPostgreSQL_LINK_LIBS};${Poco_DataPostgreSQL_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::DataPostgreSQL PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_DataPostgreSQL_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::DataPostgreSQL PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_DataPostgreSQL_COMPILE_OPTIONS_C};${Poco_DataPostgreSQL_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT DataMySQL TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Poco::DataMySQL)
        add_library(Poco::DataMySQL INTERFACE IMPORTED)
        set_target_properties(Poco::DataMySQL PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Poco_DataMySQL_INCLUDE_DIRS}")
        set_target_properties(Poco::DataMySQL PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Poco_DataMySQL_LIB_DIRS}")
        set_target_properties(Poco::DataMySQL PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Poco_DataMySQL_LINK_LIBS};${Poco_DataMySQL_LINKER_FLAGS_LIST}")
        set_target_properties(Poco::DataMySQL PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Poco_DataMySQL_COMPILE_DEFINITIONS}")
        set_target_properties(Poco::DataMySQL PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Poco_DataMySQL_COMPILE_OPTIONS_C};${Poco_DataMySQL_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET Poco::Poco)
        add_library(Poco::Poco INTERFACE IMPORTED)
    endif()
    set_property(TARGET Poco::Poco APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${Poco_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT Foundation BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Foundation_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Data BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Data_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT ActiveRecord BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_ActiveRecord_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT XML BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_XML_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT JSON BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_JSON_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Util BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Util_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Zip BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Zip_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Net BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Net_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Redis BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Redis_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Crypto BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Crypto_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT NetSSL BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_NetSSL_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT MongoDB BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_MongoDB_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT JWT BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_JWT_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Encodings BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_Encodings_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT DataSQLite BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_DataSQLite_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT DataPostgreSQL BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_DataPostgreSQL_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT DataMySQL BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Poco_DataMySQL_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
